name: Reusable workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The artifact name that shuld be uploaded
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: The result of deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}
    # secrets:
    #   some_secret:
    #     required: true
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying & uploading..."
      - name: Set result of output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT