name: Reusable workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The artifact name that shuld be uploaded
        required: false
        default: dist
        type: string
    # secrets:
    #   some_secret:
    #     required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying & uploading..."